# Generated by Django 6.0.4 on 2026-08-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_public_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apns_token",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
