# Generated by Django 6.0.3 on 2026-08-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_apns_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apns_token',
            new_name='apns_device_id',
        ),
    ]
