"""
Django settings for scoutcamservice project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'djangoinsecure-asoikdfjapoiwehfj2323894askjdf23')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rules',
    'users',
    'camera',
    'notifications',
    'events',
    'django_extensions',
    'rest_framework',
    'rest_framework_simplejwt',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scoutcamservice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scoutcamservice.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',  # Captures DEBUG and above at the handler level
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),  # Sets the global log level
    },
}

# Database
DATABASES = {
    'default': {
        'ENGINE': f'django.db.backends.{os.getenv('DATABASE_ENGINE', 'postgresql')}',
        'NAME': os.getenv('DATABASE_NAME', 'scoutcamservicedb'),
        'HOST': os.getenv('DATABASE_HOST', '127.0.0.1'),
        'PORT': os.getenv('DATABASE_PORT', 5432),
        'USER': os.getenv('DATABASE_USERNAME', 'appuser'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'lYr3KCPu6QFr8W9KHcRF7gAK2Wfp'),
        'CONN_MAX_AGE': float(os.getenv('DATABASE_CONN_MAX_AGE', 60)),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'users.User'

# 'DJANGO_ALLOWED_HOSTS' should be a single string of hosts with a, between each.
# For example: 'DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1,[::1]'
# ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1').split(',')

# TODO: DON'T LET THIS INTO PRODUCTION!!!!!
ALLOWED_HOSTS = ['*']

# AWS
AWS_REGION = os.environ.get('AWS_REGION', '')
AWS_IMG_DETECTION_BUCKET = os.environ.get('AWS_IMG_DETECTION_BUCKET', '')
AWS_IMG_PREVIEW_BUCKET = os.environ.get('AWS_IMG_PREVIEW_BUCKET', '')
AWS_ENDPOINT_URL = os.environ.get("AWS_ENDPOINT_URL", default=None)
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", default="test")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", default="test")

# Redis
REDIS_HOST = os.environ.get('REDIS_HOST', default="localhost")
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))

# Streaming
STREAMING_STATE_KEY_TTL = int(os.environ.get("STREAMING_STATE_KEY_TTL", 60))
STREAMING_LONG_POLL_TIMEOUT = int(os.environ.get("STREAMING_LONG_POLL_TIMEOUT", 25))
STREAMING_READER_SWEEP_POLL_INTERVAL = int(os.environ.get("STREAMING_READER_SWEEP_POLL_INTERVAL", 15))
STREAMING_READER_SWEEP_EMPTY_GRACE_PERIOD = int(os.environ.get("STREAMING_READER_SWEEP_EMPTY_GRACE_PERIOD", 20))
MEDIAMTX_API_URL = os.environ.get("MEDIAMTX_API_URL", default="http://localhost:9997")

# Event processing -- SQS queue carrying the S3 detection-image notifications.
SQS_QUEUE_NAME = os.environ.get('SQS_QUEUE_NAME', '')
SQS_MAX_NUMBER_OF_MESSAGES = int(os.environ.get('SQS_MAX_NUMBER_OF_MESSAGES', 10))
SQS_WAIT_TIME_SECONDS = int(os.environ.get('SQS_WAIT_TIME_SECONDS', 10))

# Rules model. Shape matches what events.ml.factory.build_rules_model expects;
# it takes a plain dict so the ml package stays free of Django imports.
ML_CONFIG = {
    'model_type': os.environ.get('ML_MODEL_TYPE', 'api'),
    'api_model_name': os.environ.get('ML_API_MODEL_NAME', 'gemini-3.1-flash-lite'),
    'hosted_model_name': os.environ.get('ML_HOSTED_MODEL_NAME'),
    'model_weights_dir': os.environ.get('ML_MODEL_WEIGHTS_DIR', 'ml_weights'),
}

# Environment Tracking
ENVIRONMENT = os.environ.get('ENV', default="dev")
DEV_IP = os.environ.get('DEV_IP', default="127.0.0.1")

# Celery
# db 1, while the streaming state keys live in db 0: a FLUSHDB while debugging
# streaming would otherwise drop every queued task with it.
CELERY_BROKER_URL = os.environ.get(
    'CELERY_BROKER_URL', default=f'redis://{REDIS_HOST}:{REDIS_PORT}/1')
# Nothing waits on a task's return value -- the work is writing rows, stopping
# streams, and sending pushes -- so results would only accumulate in Redis.
CELERY_RESULT_BACKEND = None
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
# Ack after the task returns, not when it's delivered, so a worker killed
# mid-image puts the message back instead of silently dropping it.
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# APNs
APNS_KEY_ID=os.environ.get("APNS_KEY_ID", default="")
APNS_PRIVATE_KEY_PATH=os.environ.get("APNS_PRIVATE_KEY_PATH", default="")
APNS_TEAM_ID=os.environ.get("APNS_TEAM_ID", default="")
APNS_JWT_STALE_TIME_SECONDS=int(os.environ.get("APNS_JWT_STALE_TIME_SECONDS", default=1800))
APNS_CLIENT_RETRIES = int(os.environ.get("APNS_CLIENT_RETRIES", default=3))
APNS_APP_BUNDLE_ID=os.environ.get("APNS_APP_BUNDLE_ID", default="")
APNS_URL=os.environ.get("APNS_URL", default="")
APNS_PRIORITY=int(os.environ.get("APNS_PRIORITY", default=10))


# Notifications
RULE_TRIGGER_COOLDOWN_MINUTES=int(os.environ.get("RULE_TRIGGER_COOLDOWN_MINUTES", default=2))