# Generated by Django 6.0.3 on 2026-07-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_camera_claim_token_hash_camera_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='preview_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
