# Generated by Django 6.0.3 on 2026-07-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_camera_camera_preview_url_camera_preview_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='camera_preview_url',
        ),
    ]
