scrape_configs:
  - job_name: 'MagPieCam-Core'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['magpiecam-core:8000']

  - job_name: 'MagPieCam-ML-Worker'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['rules-ml-worker:8225']

  - job_name: 'MagPieCam-Stream-Command-Worker'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['stream-command-worker:8225']