# Generated by Django 6.0.3 on 2026-08-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rule_public_rule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
