# Generated by Django 6.0.4 on 2026-08-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0005_remove_camera_camera_preview_url"),
        ("notifications", "0001_initial"),
        ("rules", "0003_rule_last_triggered"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-public_notification_id"]},
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_camera__32ffc8_idx",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["camera", "-public_notification_id"],
                name="notificatio_camera__080f94_idx",
            ),
        ),
    ]
