# Generated by Django 6.0.4 on 2026-08-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_rule_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='detection_image_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
