# Generated by Django 6.0.4 on 2026-08-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_detection_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
