# Generated by Django 6.0.4 on 2026-08-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='video_clip_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
