# Generated by Django 6.0.4 on 2026-08-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_rules_notification_rule_nicknames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
